name: Tests

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Validate composer.json
        run: composer validate --strict

      - name: Composer Audit
        run: composer audit

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run code style checks
        run: composer lint
  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        include:
          - php-version: '8.1'
          - php-version: '8.2'
          - php-version: '8.3'
          - php-version: '8.4'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Create var directory
        run: mkdir -p var

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run tests
        run: composer test